# Generated by Django 4.2.5 on 2024-01-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_following_user_userfollowing_following_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'following_user')},
        ),
    ]
